/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Personaje;

/**
 *
 * @author Nicolas olivos
 */
public class frmStats extends javax.swing.JFrame {
    /**
     * Creates new form frmStats
     */
    Personaje p;
    public frmStats(Personaje p) {
        this();
        this.p=p;
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        switch(this.p.getClass().toString()){
            case "class controlador.Arquero":
                lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texturas/arquero.jpg")));
                lblClase.setText("Clase: Arquero");
                break;
            case "class controlador.Guerrero":
                lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texturas/guerrero.jpg")));
                lblClase.setText("Clase: Guerrero");
                break;
            case "class controlador.Mago":
                lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texturas/mago.jpg")));
                lblClase.setText("Clase: Mago");
                break;
        }
        lblNombre.setText("Nombre: "+this.p.getNombre());
        this.setTitle("World of LP");
        this.setEstado();
        
    }
    public frmStats() {
        initComponents();
    }
    
    public void aumentar(){
        this.p.aumentarExp(100);
    }
    
    public void setEstado(){
        lblNivel.setText("Nivel: "+this.p.getNivel());
        lblExp.setText("Experiencia: "+this.p.getEXP()+"/"+p.expSiguienteLvl(this.p.getNivel()));
        pgbExp.setMaximum(p.expSiguienteLvl(this.p.getNivel()));
        pgbExp.setValue(this.p.getEXP());
        lblConstitucion.setText("Constitucion: "+this.p.getStats().getConstitucion());
        lblDestreza.setText("Destreza: "+this.p.getStats().getDestreza());
        lblFuerza.setText("Fuerza: "+this.p.getStats().getFuerza());
        lblInteligencia.setText("Inteligencia: "+this.p.getStats().getInteligencia());
        lblRadioVision.setText("Radio Vision: "+this.p.getStats().getRadio_vision());
        lblRapidez.setText("Rapidez: "+this.p.getStats().getRapidez());
        lblResistencia.setText("Resistencia: "+this.p.getStats().getResistencia());
        lblResistenciaMagica.setText("Resistencia Magica: "+this.p.getStats().getResistencia_magica());
        lblStamina.setText("Stamina: "+this.p.getStats().getStamina());
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlArquero = new javax.swing.JPanel();
        lblPersonaje = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblClase = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        pgbExp = new javax.swing.JProgressBar();
        lblExp = new javax.swing.JLabel();
        btnAumentar = new javax.swing.JButton();
        lblRadioVision = new javax.swing.JLabel();
        lblResistenciaMagica = new javax.swing.JLabel();
        lblRapidez = new javax.swing.JLabel();
        lblInteligencia = new javax.swing.JLabel();
        lblFuerza = new javax.swing.JLabel();
        lblStamina = new javax.swing.JLabel();
        lblDestreza = new javax.swing.JLabel();
        lblConstitucion = new javax.swing.JLabel();
        lblResistencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlArquero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonaje.setMaximumSize(new java.awt.Dimension(144, 24));
        lblPersonaje.setMinimumSize(new java.awt.Dimension(144, 24));
        lblPersonaje.setPreferredSize(new java.awt.Dimension(144, 24));

        javax.swing.GroupLayout pnlArqueroLayout = new javax.swing.GroupLayout(pnlArquero);
        pnlArquero.setLayout(pnlArqueroLayout);
        pnlArqueroLayout.setHorizontalGroup(
            pnlArqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPersonaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlArqueroLayout.setVerticalGroup(
            pnlArqueroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPersonaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setText("jLabel1");

        lblClase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClase.setText("jLabel1");

        lblNivel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNivel.setText("jLabel1");

        lblExp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExp.setText("jLabel1");

        btnAumentar.setText("aumentar");
        btnAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarActionPerformed(evt);
            }
        });

        lblRadioVision.setText("jLabel1");

        lblResistenciaMagica.setText("jLabel2");

        lblRapidez.setText("jLabel3");

        lblInteligencia.setText("jLabel4");

        lblFuerza.setText("jLabel5");

        lblStamina.setText("jLabel6");

        lblDestreza.setText("jLabel7");

        lblConstitucion.setText("jLabel8");

        lblResistencia.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAumentar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNivel)
                                .addGap(18, 18, 18)
                                .addComponent(pgbExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblExp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlArquero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblClase)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRadioVision)
                                    .addComponent(lblRapidez)
                                    .addComponent(lblFuerza)
                                    .addComponent(lblDestreza))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConstitucion)
                                    .addComponent(lblStamina)
                                    .addComponent(lblInteligencia)
                                    .addComponent(lblResistenciaMagica))))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlArquero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblClase)
                        .addGap(68, 68, 68)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgbExp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRadioVision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRapidez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFuerza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDestreza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(btnAumentar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblResistencia)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResistenciaMagica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInteligencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStamina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConstitucion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarActionPerformed
        this.aumentar();
        this.setEstado();
    }//GEN-LAST:event_btnAumentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStats().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentar;
    private javax.swing.JLabel lblClase;
    private javax.swing.JLabel lblConstitucion;
    private javax.swing.JLabel lblDestreza;
    private javax.swing.JLabel lblExp;
    private javax.swing.JLabel lblFuerza;
    private javax.swing.JLabel lblInteligencia;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JLabel lblRadioVision;
    private javax.swing.JLabel lblRapidez;
    private javax.swing.JLabel lblResistencia;
    private javax.swing.JLabel lblResistenciaMagica;
    private javax.swing.JLabel lblStamina;
    private javax.swing.JProgressBar pgbExp;
    private javax.swing.JPanel pnlArquero;
    // End of variables declaration//GEN-END:variables
}
