/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.EquipoItem;
import controlador.Item;
import controlador.Npc;
import controlador.Personaje;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class frmTrafico extends javax.swing.JFrame {

    /**
     * Creates new form frmTrafico
     */
    Personaje p;
    Npc n;
    public frmTrafico(Personaje p, Npc n){
        this();
        this.p=p;
        this.n=n;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        switch(this.p.getClass().toString()){
            case "class controlador.Arquero":
                lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texturas/arquero.jpg")));
                break;
            case "class controlador.Guerrero":
                lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texturas/guerrero.jpg")));
                break;
            case "class controlador.Mago":
                lblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texturas/mago.jpg")));
                break;
        }
        lblNombreP.setText(p.getNombre());
        lblDineroP.setText(p.getDinero()+" monedas");
        lblVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texturas/Traficante.jpg")));
        lblNombreT.setText(n.getNombre());
        lblDineroT.setText(n.getDinero()+" monedas");
        setEstado();
    }
    public frmTrafico() {
        initComponents();
    }
    
    public synchronized void setEstado() {
        //Jugador
        DefaultTableModel mdl1 =(DefaultTableModel)this.tblJugador.getModel();
        mdl1.setRowCount(0);
        for(Item it:p.getInventario().getItems()){
            Object data[]={it.getNombre(),it.getPrecio()};
            mdl1.addRow(data);
        }
        this.lblDineroP.setText(p.getDinero()+" monedas.");
        this.tblJugador.setModel(mdl1);
        //Traficante
        DefaultTableModel mdl2 =(DefaultTableModel)this.tblTraficante.getModel();
        mdl2.setRowCount(0);
        for(Item it:n.getInventario().getItems()){
            Object data[]={it.getNombre(),it.getPrecio()};
            mdl2.addRow(data);
        }
        this.lblDineroT.setText(n.getDinero()+" monedas.");
        this.tblTraficante.setModel(mdl2);        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVendedor = new javax.swing.JLabel();
        lblPersonaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreP = new javax.swing.JLabel();
        lblNombreT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJugador = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTraficante = new javax.swing.JTable();
        lblDineroP = new javax.swing.JLabel();
        lblDineroT = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendedor.setMaximumSize(new java.awt.Dimension(144, 24));
        lblVendedor.setMinimumSize(new java.awt.Dimension(144, 24));
        lblVendedor.setPreferredSize(new java.awt.Dimension(144, 24));

        lblPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonaje.setMaximumSize(new java.awt.Dimension(144, 24));
        lblPersonaje.setMinimumSize(new java.awt.Dimension(144, 24));
        lblPersonaje.setPreferredSize(new java.awt.Dimension(144, 24));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Traficante de Items");

        lblNombreP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreP.setText("jLabel2");

        lblNombreT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreT.setText("jLabel2");

        tblJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJugadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJugador);

        tblTraficante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTraficante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraficanteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTraficante);

        lblDineroP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDineroP.setText("jLabel2");

        lblDineroT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDineroT.setText("jLabel2");

        btnExit.setText("Finalizar Transacción");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNombreP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombreT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDineroP, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(lblDineroT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreP)
                    .addComponent(lblNombreT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDineroP)
                    .addComponent(lblDineroT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJugadorMouseClicked
        String objetivo=tblJugador.getValueAt(tblJugador.getSelectedRow(), 0).toString();
        
        for (EquipoItem i:Juego.jugador.getInventario().getItems()){
            if (i.getNombre().equals(objetivo)){
                Juego.jugador.getInventario().removeItem(i);
                n.getInventario().addItem(i);
                Juego.jugador.ganarDinero(i.getPrecio());
                n.gastarDinero(i.getPrecio());
                setEstado();
                break;  
            }
        }
    }//GEN-LAST:event_tblJugadorMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        n.interactuando=false;
        Juego.ventanaInventario.setEstado();
        p.releaseTeclado();
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblTraficanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraficanteMouseClicked
        String objetivo=tblTraficante.getValueAt(tblTraficante.getSelectedRow(), 0).toString();
        
        for (EquipoItem i:n.getInventario().getItems()){
            if (i.getNombre().equals(objetivo)){
                if(Juego.jugador.gastarDinero(i.getPrecio())){
                    n.getInventario().removeItem(i);
                    Juego.jugador.getInventario().addItem(i);
                    n.ganarDinero(i.getPrecio());
                }
                setEstado();
                break;  
            }
        }
    }//GEN-LAST:event_tblTraficanteMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDineroP;
    private javax.swing.JLabel lblDineroT;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblNombreT;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JTable tblJugador;
    private javax.swing.JTable tblTraficante;
    // End of variables declaration//GEN-END:variables
}
